config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root to: redirect('/users/sign_up')
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :recipes ,only: [:create, :index, :destroy, :show, :new, :update] do
    member do
      patch 'update_privacy', to: 'recipes#update_privacy', as: 'update_recipe_privacy'
    end
  end

  resources :recipe_foods, only: [:new, :create, :destroy]
  
  resources :inventories, only: [:create, :index, :show, :destroy, :new] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end

  resources :inventory_foods do
    delete 'remove_food', on: :member
  end
    
  get '/public_recipes', to:'recipes#public_recipes', as: :public_recipes
  get '/shopping_list', to:'recipes#shopping_list', as: :shopping_list

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        confirmations: 'users/confirmations'
  }
  
  resources :foods, only: [:index, :create, :destroy, :new]

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    # destroy_user_session_path << Required Later
    # root to: 'recipes#public_recipes' << Required Later
  end
  
  # devise_for :users
  # Defines the root path route ("/")
  root "recipes#public_recipes"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
  belongs_to :user
  validates :name, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[public_recipes show]
  before_action :set_ability

  def set_ability
    @ability = Ability.new(current_user)
  end

  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render 'new'
    end
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'Recipe was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    redirect_to recipes_path
  end

  def update_privacy
    @recipe = Recipe.find(params[:id])
    @recipe.toggle!(:public)
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: 'Recipe privacy updated.'
    else
      render 'edit'
    end
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user, recipe_foods: :food).where(public: true)
  end

  def shopping_list
    @recipe = Recipe.find(params[:recipe_id])
    @inventory = Inventory.find(params[:inventory_id])

    @shopping_list = []
    @total_value = 0

    @recipe.recipe_foods.each do |recipe_food|
      inventory_food = @inventory.inventory_foods.find_by(food: recipe_food.food)

      if inventory_food.nil?
        quantity_to_buy = recipe_food.quantity
        total_price = quantity_to_buy * recipe_food.food.price
      elsif inventory_food.quantity < recipe_food.quantity
        quantity_to_buy = recipe_food.quantity - inventory_food.quantity
        total_price = quantity_to_buy * recipe_food.food.price
      else
        quantity_to_buy = 0
        total_price = 0
      end

      @shopping_list << [recipe_food.food.name, quantity_to_buy, total_price]
      @total_value += total_price
    end

    @missing_foods = @recipe.recipe_foods.count - @shopping_list.size
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="bg-white p-4 md:p-6 rounded-lg shadow-md md:w-[50%] mt-3">
  <h1 class="text-3xl md:text-4xl font-semibold mb-3 md:mb-5">Welcome To Recipe Page</h1>

  <div class="mb-3 md:mb-6">
    <%= link_to new_recipe_path,
      class: "px-3 md:px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-lg cursor-pointer" do %>
      Add
      <% end %>
  </div>

  <div class="recipe-container mt-3 md:mt-5">
    <% @recipes.each do |recipe| %>
      <div
        class="recipe bg-gray-100 p-3 md:p-4 rounded-lg mb-3 md:mb-4 flex flex-col md:flex-row justify-between items-center">
        <%= link_to recipe_path(recipe), class: "info" do %>
          <h2 class="text-xl md:text-2xl font-medium mb-2 md:mb-0">
            <%= recipe.name %>
          </h2>
          <p class="text-gray-600 text-sm md:text-lg">Description: <span class="text-xs md:text-sm">
              <%= recipe.description %>
            </span>
          </p>
          <% end %>
          <% if can? :destroy, recipe %>
            <%= form_with model: recipe, url: recipe_path(recipe), method: :delete, class: "mt-3 md:mt-0" do |form| %>
              <%= form.submit "Remove" ,
                class: "px-3 md:px-4 py-1 bg-red-500 hover:bg-red-600 text-white font-medium rounded-lg cursor-pointer"
                %>
                <% end %>
                <% end %>
      </div>
      <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="bg-white p-6 rounded-lg shadow-md md:w-[50%] mt-3">
    <h1 class="text-3xl font-extrabold mb-5 text-gray-800">Add New Recipe</h1>

    <%= form_with model: @recipe, url: recipes_path, class: "text-gray-800" do |form| %>
        <div class="mb-4">
            <%= form.label :name, class: "text-lg font-medium" %>
                <%= form.text_field :name,
                    class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
        </div>
        <div class="mb-4">
            <%= form.label :preparation_time, class: "text-lg font-medium" %>
                <%= form.number_field :preparation_time, step: '0.01' ,
                    class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
        </div>
        <div class="mb-4">
            <%= form.label :cooking_time, class: "text-lg font-medium" %>
                <%= form.number_field :cooking_time, step: '0.01' ,
                    class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
        </div>
        <div class="mb-4">
            <%= form.label :description, class: "text-lg font-medium" %>
                <%= form.text_area :description,
                    class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
        </div>
        <div class="mb-4">
            <%= form.submit "Add Recipe" ,
                class: "px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-lg cursor-pointer" %>
        </div>
        <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="bg-slate-400 p-6 flex justify-center items-center flex-col">
  <h1 class="text-5xl font-semibold mb-5 text-slate-900 ">Public Recipes</h1>

  <div class="bg-slate-100 p-4 rounded-lg">
    <% if @public_recipes.empty? %>
      <p class="text-xl text-gray-600">No public recipes available.</p>
      <% else %>
        <% @public_recipes.each do |recipe| %>
          <%= link_to recipe_path(recipe), class: "block hover:shadow-md transition duration-300 rounded-lg p-4 mb-4" do
            %>
            <div class="flex items-center justify-between space-x-20">
              <div>
                <p class="text-3xl font-medium text-gray-600 mb-2">
                  <%= recipe.name %>
                </p>
                <p class="text-xl text-slate-300">By: <span class="text-slate-600">
                    <%= recipe.user.name %>
                  </span></p>
              </div>
              <div>
                <p class="text-gray-600">Food Items Count: <%= recipe.recipe_foods.count %>
                </p>
                <p class="text-gray-600">Total Price: $<%= recipe.recipe_foods.sum { |rf| rf.quantity * rf.food.price }
                    %>
                </p>
              </div>
            </div>
            <% end %>
              <% end %>
                <% end %>
  </div>
</div>

app/views/recipes/shopping_list.html.erb
<div class="p-4 border bg-white rounded mt-3">
  <h1 class="text-2xl font-semibold mb-4 flex items-center justify-center">Shopping List</h1>
  <div class="flex justify-between items-center mb-4 space-x-10">
    <div>
      <p class="text-lg">Amount of food to buy: <%= @shopping_list.size %></p>
      <p class="text-lg mt-4">Total value of food needed: $<%= @total_value %></p>
    </div>
    <div class="text-lg flex flex-col">
      <%= link_to content_tag(:span, "Recipe:", class: "text-black") + " " + @recipe.name, recipe_path(params[:recipe_id]), class: "text-blue-500 hover:underline" %> 
      <%= link_to content_tag(:span, "Inventory:", class: "text-black") + " " + @inventory.name, inventory_path(params[:inventory_id]), class: "text-blue-500 hover:underline mt-4" %>
    </div>
  </div>

<div class="flex flex-col mt-4 border bg-slate-200 rounded">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-left text-sm font-light">
          <thead class="border-b font-medium dark:border-neutral-500">
            <tr>
              <th scope="col" class="px-6 py-3 text-left">Food</th>
              <th scope="col" class="px-6 py-3 text-left">Quantity</th>
              <th scope="col" class="px-6 py-3 text-left">Price</th>
            </tr>
          </thead>
          <tbody>
            <% @shopping_list.each do |food| %>
            <tr class="border-b transition duration-300 ease-in-out hover:bg-neutral-100 dark:border-neutral-500 dark:hover:bg-neutral-600">
              <td class="whitespace-nowrap px-6 py-3"><%= food[0] %></td>
              <td class="whitespace-nowrap px-6 py-3">$<%= food[1] %></td>
              <td class="whitespace-nowrap px-6 py-3">$<%= food[2] %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

app/views/recipes/show.html.erb
<% if can? :read, @recipe %>
<div class="container mx-auto p-4">
  <div class="bg-white p-6 rounded-lg shadow-md mt-4 lg:w-1/2 mx-auto">
    <div class="bg-slate-400 p-6 text-slate-900 flex justify-center items-center flex-col">
      <h1 class="text-3xl font-semibold flex items-center justify-center">
        <%= @recipe.name %>
      </h1>
      <p class="text-xl mt-4">
        Preparation time: <%= @recipe.preparation_time %> hour
      </p>
      <div class="flex items-center justify-end space-x-4">
        <% if user_signed_in? %>
          <%= form_for @recipe, url: update_recipe_privacy_recipe_path(@recipe), method: :patch do |f| %>
            <% if can? :update, @recipe %>
            <div class="field mt-2 flex items-center space-x-3">
              <div class="text-lg font-medium text-gray-800">Public</div>
              <%= f.check_box :public, class: 'toggle-checkbox', onclick: 'this.form.submit();' %>
            </div>
            <% end %>
            <div class="field">
              <%= f.submit "" %>
            </div>
          <% end %>
        <% end %>
      </div>
      <p class="text-xl">
        Cooking time: <%= @recipe.cooking_time %> hours
      </p>
      <p class="text-xl mt-4">
        Description: <%= @recipe.description %>
      </p>
      <% if can? :update, @recipe %>
      <div class="flex gap-5 mt-4 bg-slate-100 p-6 rounded-lg shadow-md">
          <button class="bg-blue-500 text-white px-4 py-2 rounded text-xs lg:text-base hover:bg-blue-600" id="open-popup">Generate Shopping List</button>
          <%= link_to new_recipe_food_path(recipe_id: @recipe.id) do %>
            <button class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 text-xs lg:text-base">Add Ingredient</button>
          <% end %>
        </div>
        <div id="recipe-popup" class="fixed inset-0 justify-center flex items-center bg-black bg-opacity-50 hidden">
          <div class="bg-white p-8 rounded-lg h-1/2 w-1/2">
            <!-- Popup content goes here -->
            <button class="bg-red-500 text-white px-4 py-2 rounded-full hover-bg-red-600" id="close-popup">X</button>
            <h2 class="text-2xl font-semibold mt-4">Generate Shopping List</h2>
            <p>Choose an inventory to use</p>
            <%= form_tag(shopping_list_path, method: :get, id: 'shopping-list-form') do %>
              <%= hidden_field_tag :recipe_id, @recipe.id %>
              <div class="field mt-4">
                <%= label_tag :inventory_id, "Select Inventory", class: "text-lg font-medium" %>
                <%= select_tag :inventory_id, options_for_select(Inventory.all.pluck(:name, :id)), class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus-ring-2 focus-ring-blue-500" %>
              </div>
              <div class="actions mt-4">
                <%= submit_tag 'Generate', class: 'bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 cursor-pointer' %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="bg-white p-6 rounded-lg shadow-md mt-4">
  <div class="overflow-x-auto">
    <table class="min-w-full text-left text-sm font-light">
      <thead class="border-b font-medium dark:border-neutral-500">
        <tr>
          <th scope="col" class="px-6 py-4">Food</th>
          <th scope="col" class="px-6 py-4">Quantity</th>
          <th scope="col" class="px-6 py-4">Value</th>
          <% if can? :destroy, @recipe %>
            <th scope="col" class="px-6 py-4">Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |food| %>
          <tr class="border-b transition duration-300 ease-in-out hover-bg-neutral-100 dark:border-neutral-500 dark:hover-bg-neutral-600">
            <td class="whitespace-nowrap px-6 py-4"><%= food.food.name %></td>
            <td class="whitespace-nowrap px-6 py-4"><%= "#{food.quantity} #{food.food.measurement_unit}" %></td>
            <td class="whitespace-nowrap px-6 py-4">$<%= food.food.price * food.quantity %></td>
            <td class="whitespace-nowrap px-6 py-4 cursor-pointer">
              <% if can? :destroy, @recipe %>
                <%= form_with model: food, url: recipe_food_path(food), method: :delete do |form| %>
                  <%= form.submit "Remove", class: "px-4 py-2 bg-red-500 hover-bg-red-600 text-white font-medium rounded cursor-pointer" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

  </div>
</div>
<% else %>
 <%= link_to 'See Public Recipe', public_recipes_path %>
<% end %>

app/views/recipes/update.html.erb
<div class="bg-white p-6 rounded-lg shadow-md md:w-[50%] mt-3">
  <h1 class="text-3xl font-extrabold mb-5 text-gray-800">Edit Recipe</h1>

  <%= form_with(model: @recipe, url: recipe_path(@recipe), method: :patch, class: "text-gray-800") do |form| %>
    <div class="mb-4">
      <%= form.label :name, class: "text-lg font-medium" %>
      <%= form.text_field :name, class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div class="mb-4">
      <%= form.label :preparation_time, class: "text-lg font-medium" %>
      <%= form.number_field :preparation_time, step: '0.01', class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div class="mb-4">
      <%= form.label :cooking_time, class: "text-lg font-medium" %>
      <%= form.number_field :cooking_time, step: '0.01', class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div class="mb-4">
      <%= form.label :description, class: "text-lg font-medium" %>
      <%= form.text_area :description, class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div class="mb-4">
      <%= form.submit "Update Recipe", class: "px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-lg cursor-pointer" %>
    </div>
  <% end %>
</div>