config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root to: redirect('/users/sign_up')
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :recipes ,only: [:create, :index, :destroy, :show, :new, :update] do
    member do
      patch 'update_privacy', to: 'recipes#update_privacy', as: 'update_recipe_privacy'
    end
  end

  resources :recipe_foods, only: [:new, :create, :destroy]
  
  resources :inventories, only: [:create, :index, :show, :destroy, :new] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end

  resources :inventory_foods do
    delete 'remove_food', on: :member
  end
    
  get '/public_recipes', to:'recipes#public_recipes', as: :public_recipes
  get '/shopping_list', to:'recipes#shopping_list', as: :shopping_list

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        confirmations: 'users/confirmations'
  }
  
  resources :foods, only: [:index, :create, :destroy, :new]

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    # destroy_user_session_path << Required Later
    # root to: 'recipes#public_recipes' << Required Later
  end
  
  # devise_for :users
  # Defines the root path route ("/")
  root "recipes#public_recipes"
end

app/views/layouts/_navbar.html.erb
<nav
  class="relative flex w-full flex-nowrap items-center justify-between bg-neutral-800 py-2 text-neutral-500 shadow-lg hover:text-neutral-700 focus:text-neutral-700 lg:flex-wrap lg:justify-start lg:py-4 bgcolor"
  data-te-navbar-ref
>
  <button
    class="block border-0 bg-transparent px-2 text-neutral-300 hover:no-underline hover:shadow-none focus:no-underline focus:shadow-none focus:outline-none focus:ring-0 dark:text-neutral-200 lg:hidden hamburger-button"
    type="button"
    data-te-collapse-init
    data-te-target="#navbarSupportedContent9"
    aria-controls="navbarSupportedContent9"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="w-7">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        class="h-7 w-7"
      >
        <path
          d="M3 12h18M3 6h18M3 18h18"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </span>
  </button>

  <button
    class="block border-0 bg-transparent px-2 text-neutral-300 hover:no-underline hover:shadow-none focus:no-underline focus:shadow-none focus:outline-none focus:ring-0 dark:text-neutral-200 lg:hidden close-button"
    type="button"
    onclick="closeMenu()"
    style="display: none; position: absolute; top: 10px; left: 10px"
  >
    <span class="w-7">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        class="h-7 w-7"
      >
        <path
          d="M6 18L18 6M6 6l12 12"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </span>
  </button>

  <div
    id="navbarSupportedContent9"
    class="mt-5 ml-16 hidden lg:ml-0 flex-grow basis-[100%] items-center lg:mt-0 lg:!flex lg:basis-auto lg:hidden"
  >
    <ul
      class="list-style-none mx-auto flex flex-col pl-0 lg:mt-1 lg:flex-row justify-center"
      data-te-navbar-nav-ref
    >
      <li class="my-4 lg:my-0 lg:pr-1" data-te-nav-item-ref>
        <a
          class="hover:text-neutral-200 lg:px-2 focus:text-neutral-200 <%= 'active-link' if request.path == root_path %>"
          aria-current="page"
          href="<%= root_path %>"
          data-te-nav-link-ref
          >Home</a
        >
      </li>
      <% if user_signed_in? %>
      <li class="mb-4 lg:mb-0 lg:pr-1" data-te-nav-item-ref>
        <a
          class="hover:text-neutral-200 focus:text-neutral-200 lg:px-2"
          href="<%= new_food_path %>"
          data-te-nav-link-ref
          >Add Food</a
        >
      </li>
      <% end %> <% if user_signed_in? %>
      <li class="mb-4 lg:mb-0 lg:pr-1" data-te-nav-item-ref>
        <a
          class="hover:text-neutral-200 focus:text-neutral-200 lg:px-2"
          href="<%= recipes_path %>"
          data-te-nav-link-ref
          >Recipes</a
        >
      </li>
      <% end %> <% if user_signed_in? %>
      <li class="mb-4 lg:mb-0 lg:pr-1" data-te-nav-item-ref>
        <a
          class="hover:text-neutral-200 focus:text-neutral-200 lg:px-2"
          href="<%= inventories_path %>"
          data-te-nav-link-ref
          >Inventories</a
        >
      </li>
      <% end %> <% unless user_signed_in? %>
      <li class="mb-4 lg:mb-0 lg:pr-1" data-te-nav-item-ref>
        <a
          class="hover:text-neutral-200 focus:text-neutral-200 lg:px-2"
          href="<%= new_user_registration_path %>"
          data-te-nav-link-ref
          >Register</a
        >
      </li>
      <% end %> <% unless user_signed_in? %>
      <li class="mb-4 lg:mb-0 lg:pr-1" data-te-nav-item-ref>
        <a
          class="hover:text-neutral-200 focus:text-neutral-200 lg:px-2"
          href="<%= new_user_session_path %>"
          data-te-nav-link-ref
          >Log in</a
        >
      </li>
      <% end %> <% if user_signed_in? %>
      <li class="mb-4 lg:mb-0 lg:pr-1" data-te-nav-item-ref>
        <a
          class="hover:text-neutral-200 focus:text-neutral-200 lg:px-2"
          href="<%= users_sign_out_path %>"
          data-te-nav-link-ref
          >Log out</a
        >
      </li>
      <% end %>
    </ul>
  </div>
</nav>

<script>
  document.addEventListener("turbo:load", function () {
    const currentPath = "<%= request.path %>";
    const navLinks = document.querySelectorAll("[data-te-nav-link-ref]");

    navLinks.forEach((link) => {
      link.classList.remove("active-link");

      if (link.getAttribute("href") === currentPath) {
        link.classList.add("active-link");
      }
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> 
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %> 
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-400">
    <main class="flex items-center justify-center flex-col">
      <%= render "layouts/navbar" %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>